name: Deploy to Azure Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CLUSTER_NAME: "saulbot-rust"
  CLUSTER_RESOURCE_GROUP: "saul-rg"
  NAMESPACE: "saul"
  IMAGE_NAME: "saulbot-rust-image"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Login via Azure CLI'
      if: ${{ !env.ACT }}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login in to Azure registry'
      if: ${{ !env.ACT }}
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: 'Build and push image'
      run: |
        docker build --no-cache  -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      working-directory: ./
    
    - name: 'Set target AKS cluster'
      if: ${{ !env.ACT }}
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    - name: 'Create namespace'
      if: ${{ !env.ACT }}
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f - 
    
    - name: Deploy to AKS
      if: ${{ !env.ACT }}
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ./manifests/deployment.yaml
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.IMAGE_NAME}}:${{ github.sha }}'
        namespace: '${{ env.NAMESPACE }}'
    
    
